<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HG-LT-30470" failures="1" tests="5" name="APITestAssessment" time="3.823" errors="0" timestamp="2025-02-24T20:43:32 SAST">
  <testcase classname="AuthLogin" name="Login" time="2.836">
    <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at AuthLogin.Login(AuthLogin.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
  <testcase classname="AuthLogin" name="InvalidPassword" time="0.223"/>
  <testcase classname="AuthLogin" name="PINRequired" time="0.222"/>
  <testcase classname="AuthLogin" name="UserCredentialsRequired" time="0.233"/>
  <testcase classname="AuthLogin" name="MSISDNRequired" time="0.222"/>
</testsuite> <!-- APITestAssessment -->
